name: build

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and Publish head Docker image
      uses: VaultVulp/gp-docker-action@1.1.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: JimmyBotTS

    - name: Deploy package to Digital Ocean
      uses: appleboy/ssh-action@master
      env:
        GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        host: ${{ secrets.DA_HOST }}
        username: ${{ secrets.DA_USERNAME }}
        key: ${{ secrets.DA_KEY }}
        port: ${{ secrets.DA_PORT }}
        script: whoami