name: build

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and Publish head Docker image
      uses: VaultVulp/gp-docker-action@1.1.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: JimmyBotTS

    - name: Copy docker-compose file to server
      uses: appleboy/scp-action@master
      with: 
        host: ${{ secrets.DA_HOST }}
        username: ${{ secrets.DA_USERNAME }}
        key: ${{ secrets.DA_KEY }}
        port: ${{ secrets.DA_PORT }}
        source: "docker-compose.yml"
        target: "/opt/jimmy/"
      
    - name: Deploy package to Digital Ocean
      uses: appleboy/ssh-action@master
      env:
        GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      with:
        host: ${{ secrets.DA_HOST }}
        username: ${{ secrets.DA_USERNAME }}
        key: ${{ secrets.DA_KEY }}
        port: ${{ secrets.DA_PORT }}
        envs: GITHUB_USERNAME, BOT_TOKEN
        script: |
          cd /opt/jimmy/
          echo $PWD
          docker-compose pull
          docker-compose up -d
          