name: build

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and Publish head Docker image
      uses: VaultVulp/gp-docker-action@1.1.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: JimmyBotTS

    - name: Deploy package to Digital Ocean
      uses: appleboy/ssh-action@master
      env:
        GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      with:
        host: ${{ secrets.DA_HOST }}
        username: ${{ secrets.DA_USERNAME }}
        key: ${{ secrets.DA_KEY }}
        port: ${{ secrets.DA_PORT }}
        envs: GITHUB_USERNAME, DOCKER_TOKEN, BOT_TOKEN
        script: |
          docker stop $(docker ps -a -q)
          docker pull docker.pkg.github.com/rutgeruijtendaal/jimmyts/jimmybotts:latest
          docker run -dit --env BOT_TOKEN=$BOT_TOKEN docker.pkg.github.com/rutgeruijtendaal/jimmyts/jimmybotts:latest